### ISSUE TITLE
After the packaging of the document class constructor named undefined

### ISSUE THREAD

**Issue by rxliuli** [fliegwerk/fliegdoc#40] opened 2021-01-26 14:48 UTC
**Describe the bug**

After packaging the document, the constructor of the class is named `undefined`

**To Reproduce**
Steps to reproduce the behavior. 1:

1. write a class
2. then add a constructor
3. Generate a document to view
4. see the constructor as `undefined`

**Expected behavior**

should be `constructor`

**Screenshots**

![image](https://user-images.githubusercontent.com/24560368/105859783-de082980-6027-11eb-9a94-f2fef011711d.png)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [chrome]
- Version [^0.4.4]

**Additional context**

Reproducible address: https://util.liuli.moe/@liuli-util/async/#AsyncArray.constructor

**Comment by pklaschka** [comment] 2021-01-26 16:32
Thanks for opening the issue. This is actually a duplicate of #37, which I fixed a few days ago and will be fixed in the next release :wink:

**Closed by pklaschka** 2021-01-26 16:32 UTC
Labels: :bug: bug, :link: duplicate
